server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: chat
          uri: http://localhost:7070
          predicates:
            - Path=/api/chat/**
        - id: weather
          uri: http://localhost:9090
          predicates:
            - Path=/api/weather/**
